package it.polimi.ingsw.is25am33.client.view;

public enum ClientState {
    REGISTER,
    MAIN_MENU,
    CREATE_GAME_CHOOSE_NUM_PLAYERS,
    CREATE_GAME_CHOOSE_IS_TEST_FLIGHT,
    CREATE_GAME_CHOOSE_COLOR,
    JOIN_GAME_CHOOSE_GAME_ID,
    JOIN_GAME_CHOOSE_COLOR,
    WAIT_FOR_PLAYERS,
    BUILDING_SHIPBOARD_MENU,
    BUILDING_SHIPBOARD_WITH_FOCUSED_COMPONENT,
    PLACE_FOCUSED_COMPONENT,
    BUILDING_SHIPBOARD_PICK_VISIBLE_COMPONENT,
    WATCH_LITTLE_DECK, BUILDING_SHIPBOARD_PICK_RESERVED_COMPONENT;
    // TODO: add more states
}
