package it.polimi.ingsw.is25am33.client.view.tui;

public enum ClientState {
    REGISTER,
    MAIN_MENU,
    CREATE_GAME_CHOOSE_NUM_PLAYERS,
    CREATE_GAME_CHOOSE_IS_TEST_FLIGHT,
    CREATE_GAME_CHOOSE_COLOR,
    JOIN_GAME_CHOOSE_GAME_ID,
    JOIN_GAME_CHOOSE_COLOR,
    WAIT_FOR_PLAYERS,
    BUILDING_SHIPBOARD_MENU,
    BUILDING_SHIPBOARD_WITH_FOCUSED_COMPONENT,
    PLACE_FOCUSED_COMPONENT,
    BUILDING_SHIPBOARD_PICK_VISIBLE_COMPONENT,
    WATCH_LITTLE_DECK,
    BUILDING_SHIPBOARD_PICK_RESERVED_COMPONENT,
    BUILDING_SHIPBOARD_WAITING,
    BUILDING_SHIPBOARD_SELECT_PREFAB,
    CHECK_SHIPBOARD_INVALID,
    CHECK_SHIPBOARD_CHOOSE_COMPONENT_TO_REMOVE,
    CHECK_SHIPBOARD_CHOOSE_SHIP_PART_TO_KEEP,
    CHECK_SHIPBOARD_CORRECT,
    PLACE_PLACEHOLDER,
    CREW_PLACEMENT_MENU,
    NO_CREW_TO_PLACE,
    WAITING_FOR_SERVER,

    // Card-related states - general
    PLAY_CARD,
    WAITING_FOR_CARD_STATE,

    // Visit/decision states
    VISIT_LOCATION_MENU,
    CANNOT_VISIT_LOCATION,
    ACCEPT_REWARD_MENU,

    // Component selection states
    CHOOSE_CANNONS_MENU,
    CHOOSE_CANNONS_SELECT_BATTERY,
    CHOOSE_ENGINES_MENU,
    CHOOSE_ENGINES_SELECT_BATTERY,
    CHOOSE_CABIN_MENU,
    CHOOSE_STORAGE_MENU,

    // Planet selection
    CHOOSE_PLANET_MENU,

    // Dangerous object states
    HANDLE_SMALL_DANGEROUS_MENU,
    HANDLE_SMALL_DANGEROUS_SELECT_SHIELD,
    HANDLE_SMALL_DANGEROUS_SELECT_BATTERY,
    HANDLE_BIG_METEORITE_MENU,
    HANDLE_BIG_METEORITE_SELECT_CANNON,
    HANDLE_BIG_METEORITE_SELECT_BATTERY,
    HANDLE_BIG_SHOT_MENU,

    // Special events
    THROW_DICES_MENU,
    EPIDEMIC_MENU,
    STARDUST_MENU,
    HANDLE_CUBES_REWARD_MENU,
    HANDLE_CUBES_MALUS_MENU,
    CANNOT_ACCEPT_CUBES_REWARDS,
    CONFIRM_REDISTRIBUTION,
    HANDLE_INFECTED_CREW_REMOVAL,

    END_GAME_PHASE,
    CHOOSE_BATTERY_CUBES,
    CHOOSE_STORAGE_FOR_CUBEMALUS,

    CHOOSE_CANNONS_SELECT_BATTERY_BIGMETEORITE,
    WAIT_PLAYER, CHECK_SHIPBOARD_AFTER_ATTACK,
    EVALUATE_CREW_MEMBERS_MENU;
}